from ...config import settings

SILICONFLOW_API_KEY = settings.SILICONFLOW_API_KEY
SILICONFLOW_BASE_URL = settings.SILICONFLOW_BASE_URL
SILICONFLOW_MODEL = settings.SILICONFLOW_MODEL

CROSSREF_API_URL = settings.CROSSREF_API_URL
CROSSREF_EMAIL = settings.CROSSREF_EMAIL

SEMANTIC_SCHOLAR_API_URL = settings.SEMANTIC_SCHOLAR_API_URL
SEMANTIC_SCHOLAR_API_KEY = settings.SEMANTIC_SCHOLAR_API_KEY

REQUEST_TIMEOUT = 30
REQUEST_RETRY = 3
REQUEST_DELAY = 1.0
